bookings/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bookings'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('seats/',views.Seat.as_view(),name='seats'),
    path('seats/<int:pk>',views.Seat.as_view(),name='seats'),
    path('register',views.RegisterView,name='register'),
    path('login',views.user_login,name='user_login'),
    path('logout',views.user_logout,name = 'logout'),
    path('paymentgateway/',views.ReservationView,name = 'reserve'),
    path('seats/payment',views.PaymentView,name = 'payment'),
    path('ticket/',views.TicketBill.as_view(),name = 'ticket'),
    path('profile',views.profile.as_view(),name = 'profile'),
    path('suitcases',views.suitcasesHome.as_view(),name='suitcases'),
    path('straws',views.strawHome.as_view(),name='straw'),

    path('plates',views.platesHome.as_view(),name='plates'),
    path('pens',views.penHome.as_view(),name='pens'),
    path('brushes',views.brushHome.as_view(),name='brushes'),

    path('towels',views.towelHome.as_view(),name='towels'),

    path('product/<int:pk>',views.product_details.as_view(),name='product_details'),
    path('export',views.export,name='export'),

]

moviecorner/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bookings.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecom EXP</title>



<style>
  body{
    background-color:rgb(235, 229, 229);
  }
 td,th{
   padding:5px;
   width:250px;
   text-align: center;
 }
</style>
</head>
<body>
    
  <nav class="navbar navbar-expand-lg navbar-light  fixed-top " style="background:black;">
    <a class="navbar-brand" href="{% url 'bookings:home' %}" style="font-size: 1.5em;margin-left:20px;margin-right:50px;">
     <div >
      
      <b style="color: white;">
        
        
        Shopping

      </b>
     </div>
      
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav" style="">
        <a class="nav-item nav-link active" style="margin-left: px;color:white;" href="{% url 'bookings:home' %}"><b>Home</b> <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link active" style="margin-left: px;" href="{% url 'bookings:home' %}"><b></b> <span class="sr-only">(current)</span></a>

        <input class="" 
        style="background:white; border:1px solid grey; height:45px; color:black;
        border-radius:5px;margin-left: 0px;margin-right:100px; padding:5px; width:600px;
        "
        
        type="search" placeholder="Search" aria-label="Search">


        {% if user.is_authenticated %}
        <a class="nav-item nav-link"  style="margin-left: px;color:white;" href="#"><b><span style="font-size: 12px;;">Shopping pay </span> <br> Balance:{{user.userprofile.balance}}rs</b></a>

        {% if user.is_superuser %}
        <a type='button'  class="nav-item nav-link" href="{% url 'bookings:profile' %}">
   
            <img src="{{user.userprofile.profilePic.url}}" width="30px;" height="30px;" style="border-radius:50%;" alt="">
            {{user.username}}
            <br>        <a class="nav-item nav-link"  style="margin-left: px;color:white;" href="{% url 'bookings:logout' %}"><b>Logout</b></a>

        
    </a>

          {% else %}
          <a type='button'  class="nav-item nav-link" href="{% url 'bookings:profile' %}">
   
            <img src="{{user.userprofile.profilePic.url}}" width="30px;" height="30px;" style="border-radius:50%;" alt="">
            <span style="color: white;">Hello, {{user.username}}
              

              <br>        <a class="nav-item nav-link"  style="margin-left: px;color:white;" href="{% url 'bookings:logout' %}"><b>Logout</b></a>

            </span>
        
    </a>


          {% endif %}




        {% else %}
        <a class="nav-item nav-link" style="#cccccc;color:white; font-size:12px;
        " href="{% url 'bookings:user_login' %}">Hello, User <b><br><span style="font-size: 14px;">Login now</span></b></a>
        <a class="nav-item nav-link" style="#cccccc;color:white;
        " href="{% url 'bookings:register' %}"><b>sign up</b></a>
        {% endif %}
      </div>
<div>
  
</div>
      
    </div>
    
  </nav>

  

  

  <br><br> <br>
  
  {% block body_block %}



  {% endblock %}

<footer>
  <div style="background-color: rgb(32, 32, 61); ">

    <center><h6 style="color: white; padding:10px;">
      Happy Shopping !
    </h6></center>

  </div>


  <div style="background-color: rgb(16, 16, 43);color:darkgray; margin-top:-8px;">
   <center>
    <table  style="border:none;">
      <thead style="color: white;">
        <th>Get to know us</th>
        <th>Connect with us</th>
        <th>Make money with us</th>
        <th>Let us help you</th>
      </thead>
     <tbody>
      <tr>
        <td>About Us</td>
        <td>Facebook</td>
        <td>Sell on shopping</td>
        <td>Covid-19 and Shopping</td>
      </tr>
      <tr>
        <td>About Us</td>
        <td>Facebook</td>
        <td>Sell on shopping</td>
        <td>Covid-19 and Shopping</td>
      </tr>
      <tr>
        <td>About Us</td>
        <td>Facebook</td>
        <td>Sell on shopping</td>
        <td>Covid-19 and Shopping</td>
      </tr>
      <tr>
        <td>About Us</td>
        <td>Facebook</td>
        <td>Sell on shopping</td>
        <td>Covid-19 and Shopping</td>
      </tr>
      <tr>
        <td>About Us</td>
        <td>Facebook</td>
        <td>Sell on shopping</td>
        <td>Covid-19 and Shopping</td>
      </tr>
     </tbody>
    </table>
    

   </center>

   <hr style="background-color:grey ; width:1200px">
<div>
 <center>

    
  <b style="color: white;">
        
        
  <h5>  <b>
    Shopping
  </b></h5>

  </b>


<br>
  <thead>

    <th>Australia</th>
    <th>Brazil</th>
    <th>Canada</th>
    
    <th>United States</th>
    <th>Germany</th>
    <th>France</th>
    
    <th>India</th>
    <th>South Africa</th>
    <th>Netherlands</th>
    
    <th>Australia</th>
    <th>Brazil</th>
    <th>Canada</th>
    
    <th>Australia</th>
    <th>Brazil</th>
    <th>Canada</th>


  </thead>

 </center>
</div>


<br><br>

  </div>

<center>
  <div style="background-color: rgb(8, 3, 29); padding:10px;"> 
    <h6 style="color: grey;">
      Conditions of Use & Sale &nbsp; Privacy Notice &nbsp; Interest-Based Ads
      
      &nbsp;&nbsp;
      
      © 1996-2020, Shopping.com, Inc. or its affiliates
    </h6>
  </div>
</center>

</footer>

</body>
</html>

templates/brush.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}


<style>















    #fade {
        display: none;
        position: fixed;
        top: 0%;
        left: 0%;
        width: 100%;
        height: 100%;
        background-color: black;
        z-index: 1001;
        -moz-opacity: 0.8;
        opacity: .80;
        filter: alpha(opacity=80);
      }
      
      #light {
        display: none;
        position: absolute;
        top: 50%;
        left: 50%;
        max-width: 600px;
        max-height: 360px;
        margin-left: -300px;
        margin-top: -180px;
      
       
        z-index: 1002;
        overflow: visible;
      }
      
      #boxclose {
        float: right;
        cursor: pointer;
        color: #fff;
        border: 1px solid #AEAEAE;
        border-radius: 3px;
        background: #222222;
        font-size: 31px;
        font-weight: bold;
        display: inline-block;
        line-height: 0px;
        padding: 11px 3px;
        position: absolute;
        right: 2px;
        top: 2px;
        z-index: 1002;
        opacity: 0.9;
      }
      
      .boxclose:before {
        content: "×";
      }
      
      #fade:hover ~ #boxclose {
        display:none;
      }
      
      .test:hover ~ .test2 {
        display: none;
      }



























    video{
        border: 2px solid grey;
    }
    input[type=checkbox]{
        display: inline-block;
width: 32px;
height: 32px;



    }
    input[type=checkbox]:hover{
        display: inline-block;
width: 32px;
height: 32px;
background-color:#ccc;


    }
    input[type=checkbox]:checked{
   
    box-shadow: 0px 0px 20px green;

    }
    
    label{
        color: white;
    }

    #ivb{
       
      
    }
    body{
      background-color: white;
    }
    
</style>






<div class="container" style="padding:20px;">

<center>
<table>

  <thead>

    {% for i in movie %}
    {% if i.Type == "Brush" %}
    <th>
    
      <img src="{{i.poster.url}}" alt="" style="height: 18em;">
    <br>
    <h5>{{i.name}}</h5>
    <h6>{{i.description}}</h6>
    <h3>₹ {{i.basic_price}}</h3>
    
    <img class="card-img-top" src="{% static 'images/star.ico' %}" style="width:20px;" alt="Card image cap">
    <img class="card-img-top" src="{% static 'images/star.ico' %}" style="width:20px;" alt="Card image cap">
    <img class="card-img-top" src="{% static 'images/star.ico' %}" style="width:20px;" alt="Card image cap">
    <img class="card-img-top" src="{% static 'images/star.ico' %}" style="width:20px;" alt="Card image cap">
    {% if i.basic_price == 3200 %}
    <img class="card-img-top" src="{% static 'images/star.ico' %}" style="width:20px;" alt="Card image cap">
    {% else %}

    <img class="card-img-top" src="{% static 'images/halfstar.png' %}" style="width:20px;" alt="Card image cap">


    {% endif %}
    <br>
    <a href="{% url 'bookings:product_details' pk=i.pk%}" style="font-family: calibri;">Buy this..</a>
    
    </th>
    {% endif %}
    {% endfor %}
  </thead>
</table>


</center>

</div>












{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<style>
  .container {
    position: relative;
    text-align: center;
    color: rgb(255, 254, 254);
  }
  ::-webkit-scrollbar {
    display: none;
}

  
  .bottom-left {
    position: absolute;
    bottom: 8px;
    left: 16px;
  }
  
  .top-left {
    position: absolute;
    top: 8px;
    left: 16px;
  }
  
  .top-right {
    position: absolute;
    top: 8px;
    right: 16px;
  }
  
  .bottom-right {
    position: absolute;
    bottom: 8px;
    right: 16px;
  }
  
  .centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }


.card{
  margin-right:50px;
}

  div.scrollmenu {
    background-color:;
   
    overflow: auto;
    white-space: nowrap;
  }
  div.scrollmenu a {
    display: inline-block;
    color: white;
    text-align: center;
    
    text-decoration: none;
  }
  div.scrollmenu p {
    width: ;
    color: black;
    
  }
  
  div.scrollmenu a:hover {
    
   border:1px solid rgb(146, 134, 134);
    
    
    
  }
  #banner{
       
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    animation-name: bannerani;
    animation-iteration-count: infinite;
    animation-duration: 25s;
}
@keyframes bannerani {

    25%{
      content:url("{% static 'images/f1.png' %}");
     
    }
    50%{
      content:url("{% static 'images/f2.jpg' %}");
    }
   

    75%{
            content: url("{% static 'images/f1.png' %}");
        }
}


</style>
<nav class="navbar navbar-expand-lg navbar-dark "  style="margin-top:-2px;background:rgb(11, 22, 59) ;font-weight:bold;">
  <img src="{% static 'images/loco.png' %}" style="width:15px;" alt="">

  <a class="navbar-link" href="#" style="color: white;margin-left:5px;">

   <span style="font-size: 12px;"> Deliver to</span>
    {% if user.is_authenticated %}
    {{user.username}}
<br>
{{user.userprofile.Location}}
{% endif %}

  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Mobiles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Laptops</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Customer service</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'bookings:profile' %}">My orders</a>
      </li>
    </ul>
  </div>
</nav>


<img class="d-block w-100" id="banner" src="{% static 'images/back1.jpg' %}" height="600px;" style="margin-top: -50px;" alt="First slide">


<div style="background:black;">
  
  
  <center>
    <br>
    <h2 style="color: red;">OFFER ALERT</h2>
    <h3 style="color: white;">10% Discount on Carry bags</h3>
    <br>
  
  </center>
 
</div>

<center>



  <div style="margin:15px;">

    <table>
      <thead>
  
        <th ">
          <a href="{% url 'bookings:straw' %}" style="color: black; text-decoration:none; ">
          <div class="card" style="width: 18rem;height:25em; ">

<center>            <img class="card-img-top" src="{% static 'images/strawsCover.jpg' %}" style="width:200px;" alt="Card image cap">
</center>  
            <div class="card-body">
              <h5 class="card-title">Straws</h5>
              <p class="card-text">High Quality Straws At Great Prices</p>
              <a href="{% url 'bookings:straw' %}" class="btn btn-warning" style="width: 15em;;">Show more</a>
            </div>
          </div>
        </a>
        </th>
        <th>
    <a href="{% url 'bookings:plates' %}" style="color: black; text-decoration:none;">

      <div class="card" style="width: 18rem;height:25em;">
        <center>            <img class="card-img-top" src="{% static 'images/platesCover.jpg' %}" style="width:200px;" alt="Card image cap">
        </center>            <div class="card-body">
          <h5 class="card-title">Plates</h5>
          <p class="card-text">High Quality Plates At Great Prices</p>
          <a href="{% url 'bookings:plates' %}" class="btn btn-warning" style="width: 15em;">Show more</a>
        </div>
      </div>
    </a>
        </th>
        <th>
          <a href="{% url 'bookings:suitcases' %}" style="color: black; text-decoration:none;">

          <div class="card" style="width: 18rem;height:25em;">
            <center>            <img class="card-img-top" src="{% static 'images/bag.png' %}" style="height:12em; width:10em;" alt="Card image cap">
            </center>
                      <div class="card-body">
              <h5 class="card-title">Carry Bags</h5>
              <p class="card-text">High Quality Bags At Great Prices  </p>
              <a href="{% url 'bookings:suitcases' %}" class="btn btn-warning" style="width: 15em;">Show more</a>
            </div>
          </div>
          </a>
        </th>
  
      </thead>

      <tbody>
        <tr>
          <td>
            <a href="{% url 'bookings:pens' %}" style="color: black; text-decoration:none;">

              <div class="card" style="width: 18rem;height:25em;">
                <center>            <img class="card-img-top" src="https://www.parkerpen.com/dw/image/v2/BFGF_PRD/on/demandware.static/-/Sites-parkerpen-Library/default/dwf3906004/Parker/01%20JAN/50-50/201772385-Parker-Browse-by-Collection-Desktop-Tablet-Homepage-50-50_v2.jpeg" style="height:12em; width:10em;" alt="Card image cap">
                </center>
                          <div class="card-body">
                  <h5 class="card-title">Pens</h5>
                  <p class="card-text"><b>High Quality Pens At Great Prices  </b></p>
                  <a href="{% url 'bookings:pens' %}" class="btn btn-warning" style="width: 15em;">Show more</a>
                </div>
              </div>
              </a>
          </td>
          <td>
            <a href="{% url 'bookings:towels' %}" style="color: black; text-decoration:none;">

              <div class="card" style="width: 18rem;height:25em;">
                <center>            <img class="card-img-top" src="{% static 'images/towel.png' %}" style="height:12em; width:10em;" alt="Card image cap">
                </center>
                          <div class="card-body">
                  <h5 class="card-title">Towels</h5>
                  <p class="card-text"><b>High Quality Towels At Great Prices</b>  </p>
                  <a href="{% url 'bookings:towels' %}" class="btn btn-warning" style="width: 15em;">Show more</a>
                </div>
              </div>
              </a>
          </td>
          <td>
            <a href="{% url 'bookings:brushes' %}" style="color: black; text-decoration:none;">

              <div class="card" style="width: 18rem;height:25em;">
                <center>            <img class="card-img-top" src="{% static 'images/brush.png' %}" style="height:12em; width:10em;" alt="Card image cap">
                </center>
                          <div class="card-body">
                  <h5 class="card-title">Tooth Brushes</h5>
                  <p class="card-text"><b>High Quality Tooth Brushes At Great Prices </b> </p>
                  <a href="{% url 'bookings:brushes' %}" class="btn btn-warning" style="width: 15em;">Show more</a>
                </div>
              </div>
              </a>
          </td>
        </tr>

      </tbody>
    </table>
  
  </div>



</center>

 </div>




 

{% endblock %}

templates/login.html
{% load static %}
{% block body_block %}



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>
    body{
        background: url("{% static 'images/back1.jpg' %}");
    }
    .dd{
        width: 400px;
        margin: 20px;
        font-size: 25px;
        padding: 5px;
        
    }
    body{
        background-color:;
    }
</style>
<center><h1 style="color: black; margin-top:70px;">
    <b>shopping.in</b><br>
</h1></center>

<center>
    

    <div style="margin-top:10px;background-image:linear-gradient(to bottom,rgba(0,0,0.1),rgba(255,255,255,0.2));width:500px;" >


     

        <form method="POST" action="{% url 'bookings:user_login' %}">
    
            {% csrf_token %}
        
        <br>
            <input type="text" class="dd" name="username" id="" placeholder="username" required>
        <br>
            <input type="password" class="dd" name="password" id="" placeholder="password" required>
            <br>
            <input type="submit"  class="dd" class="btn btn-success" name="" value="Login" id="" >
        
        </form>
        
    </div>
    <p style="color: white;">
        Not a registered user? 
    </p>
    <a href="{% url 'bookings:register' %}" class="btn btn-warning" style="margin-top: 15px; margin-bottom:15px;">register now</a>

</center>
{% endblock %}









<!-- aUG=Kb7RHtrw)33(d9vvOnANK6tz@b$s -->

templates/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}


<style>















    #fade {
        display: none;
        position: fixed;
        top: 0%;
        left: 0%;
        width: 100%;
        height: 100%;
        background-color: black;
        z-index: 1001;
        -moz-opacity: 0.8;
        opacity: .80;
        filter: alpha(opacity=80);
      }
      
      #light {
        display: none;
        position: absolute;
        top: 50%;
        left: 50%;
        max-width: 600px;
        max-height: 360px;
        margin-left: -300px;
        margin-top: -180px;
      
       
        z-index: 1002;
        overflow: visible;
      }
      
      #boxclose {
        float: right;
        cursor: pointer;
        color: #fff;
        border: 1px solid #AEAEAE;
        border-radius: 3px;
        background: #222222;
        font-size: 31px;
        font-weight: bold;
        display: inline-block;
        line-height: 0px;
        padding: 11px 3px;
        position: absolute;
        right: 2px;
        top: 2px;
        z-index: 1002;
        opacity: 0.9;
      }
      
      .boxclose:before {
        content: "×";
      }
      
      #fade:hover ~ #boxclose {
        display:none;
      }
      
      .test:hover ~ .test2 {
        display: none;
      }



























    video{
        border: 2px solid grey;
    }
    input[type=checkbox]{
        display: inline-block;
width: 32px;
height: 32px;



    }
    input[type=checkbox]:hover{
        display: inline-block;
width: 32px;
height: 32px;
background-color:#ccc;


    }
    input[type=checkbox]:checked{
   
    box-shadow: 0px 0px 20px green;

    }
    
    label{
        color: white;
    }

    #ivb{
       
      
    }
    body{
      background-color: white;
    }
    
</style>



<br><br>
<a href="">
  
<div class="container"><p>Shopping  > {{movie.name}}</p></div>
</a>

<div id="ivb" style=" overflow-y:hidden; margin-top:50px;">
    

  <img src="{{movie.poster.url}}" style="float:left; margin-left:100px;" width="350px; " alt="">

<div style="background:white; margin-left:550px; width:500px;">

    <br>


    
    <h5 style="font-family: arial;"> {{movie.name }}</h5>
    <h6>{{movie.description}}</h6>
   
    <p>
<span style="background-color: yellow; padding:5px; border-radius:50%;"> <b>{{movie.rating}}</b></span>
      
      1,085 ratings</p>
    <hr style="width: 400px; margin-left:0px; color:black;"> 
    <p style="width: 700px;">  M.R.P<b>  <span style="text-decoration: line-through;">{{movie.basic_price}}</span> Rs/-</b>  </p>

    <p style="width: 700px;">  Price: <b>  <span style="text-decoration: line-through;">{{movie.basic_price}}</span> Rs/-</b>  </p>
    <p style="width: 700px;">  Deal Price: <b>  <span style=""> ₹ {{movie.basic_price}}</span></b> 
   <b> <span style="color:skyblue;">Shopping</span> </b>

    </p>
<hr>
    <img src="{% static 'images/thirty.PNG' %}" style=" " alt="">
<hr>
<p style="color:green; font-size:20px;">In stock.</p>


<h6 class="btn-danger"><center>Please Note the name of product while ordering</center></h6>

<div style="margin-bottom:15px;">
  {% if user.is_authenticated %}
  <a href="{% url 'bookings:reserve' %}"  class="btn btn-warning" style=" border-radius:0px;padding:15px; font-size:15px;"><b>Order Now</b></a>
  {% else %}
  <a href="{% url 'bookings:user_login' %}"  class="btn btn-warning" style=" border-radius:0px;padding:15px; font-size:20px;"><b>Order Now</b></a>

  {% endif %}

</div>


       

</div>





</div>

















{% endblock %}

templates/reservation.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}


<style>






    @import url('https://fonts.googleapis.com/css?family=Lato&display=swap');

    * {
      box-sizing: border-box;
    }
    
    body {
      color: black;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
      font-family: 'Lato', sans-serif;
      margin: 0;
    }
    
    .movie-container {
      margin: 20px 0;
    }
    
    .movie-container select {
      background-color: #fff;
      border: 0;
      border-radius: 5px;
      font-size: 14px;
      margin-left: 10px;
      padding: 5px 15px 5px 15px;
      -moz-appearance: none;
      -webkit-appearance: none;
      appearance: none;
    }
    
    .container {
      perspective: 1000px;
      margin-bottom: 30px;
    }
    
    .seat {
      background-color: #444451;
      height: 20px;
      width: 25px;
      margin: 30px;
     
      border-top-left-radius: 10px;
      border-top-right-radius: 10px;
    }
    
    .seat.selected {
      background-color: #6feaf6;
    }
    
    .seat.occupied {
      background-color: #fff;
    }
    
    .seat:nth-of-type(2) {
      margin-right: 18px;
    }
    
    .seat:nth-last-of-type(2) {
      margin-left: 18px;
    }
    
    .seat:not(.occupied):hover {
      cursor: pointer;
      transform: scale(1.2);
    }
    
    .showcase .seat:not(.occupied):hover {
      cursor: default;
      transform: scale(1);
    }
    
    .showcase {
      background: rgba(0, 0, 0, 0.1);
      padding: 5px 10px;
      border-radius: 5px;
      color: #777;
      list-style-type: none;
      display: flex;
      justify-content: space-between;
    }
    
    .showcase li {
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 10px;
    }
    
    .showcase li small {
      margin-left: 2px;
    }
    
    .row {
      display: flex;
    }
    
    .screen {
      background-color: #fff;
      height: 70px;
      width: 100%;
      margin: 15px 0;
      transform: rotateX(-45deg);
      box-shadow: 0 3px 10px rgba(255, 255, 255, 0.7);
    }
    
    p.text {
      margin: 5px 0;
    }
    
    p.text span {
      color: #6feaf6;
    }
    





</style>

<center>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <div style="margin:50px; background:white;">
     {% if booked %}
     <br><br>
<h5>Pay online or Cash on Delivery?</h5>
     <a type="submit" href="{% url 'bookings:payment' %}" class="btn btn-success" name="">Pay online</a>
     <a type="submit" href="{% url 'bookings:home' %}" class="btn btn-success" name="">Cash on delivery</a>
     <br><br>
  
 {% else %}
 
 
<script>
  alert("Please Note the name of product while ordering !");
</script>
     <div>
         <center><h1 style="color: grey;">Payment gateway</h1></center>
         <form method="POST" enctype="multipart/form-data">
             {% csrf_token %}

            <p>Order item</p>
             {{ticket_form.movie}} <br>
             
             {{ticket_form.user}} <br>
          

             <table>
               <thead>
                 <th>Order Details</th>
                 <th></th>
               </thead>
               <tbody>
                 <tr>
                   <td>Customer name:</td>
                   <td>{{user.username}}</td>
                 </tr>
                 <tr>
                  <td>Gender:</td>
                  <td>{{user.userprofile.gender}}</td>
                </tr>
                <tr>
                  <td>Age:</td>
                  <td>{{user.userprofile.age}}</td>
                </tr>
                <tr>
                  <td><b>Mobile Number</b>:</td>
                  <td>{{user.userprofile.mobilenumber}}</td>
                </tr>
               
                <tr>
                  <td><b>Delivery location</b>:</td>
                  <td>{{user.userprofile.Location}}</td>
                </tr>
               </tbody>
             </table>


<br>
             
             <button type="submit" style="border-radius: 0%;" class="btn btn-warning" name="">Place order</button>
             </form>
             <br><br>
     </div>

 {% endif %}
    </div>



    







{% endblock %}